# src/main/resources/application-dev.yml
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://asdnn.com:45306/school_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:school_user}
    password: ${MYSQL_PASSWORD:school_pass123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000

  # 开发环境下的JPA配置
  jpa:
    hibernate:
      ddl-auto: none  # 开发环境自动更新表结构
    generate-ddl: false   # 不生成DDL
    naming:
      # 关键配置：保持表名和列名的原始大小写
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 数据初始化配置 - 禁用SQL脚本执行
  sql:
    init:
      mode: never  # 不执行任何SQL初始化脚本

  # 开发环境下禁用缓存
  cache:
    type: simple

# 开发环境日志配置
logging:
  level:
    root: INFO
    com.school.course: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

server:
  port: 45081
  error:
    include-stacktrace: always  # 开发环境显示完整错误堆栈
