# src/main/resources/application.yml
server:
  port: 45081

spring:
  profiles:
    active: dev
  application:
    name: student-course-system

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        # 注意：这里的配置格式要正确
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    generate-ddl: false   # 不生成DDL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  # 数据初始化配置 - 只加载 data.sql，不加载 schema.sql
  sql:
    init:
      mode: never  # 改为 never，避免执行任何SQL脚本
      # data-locations: classpath:data.sql  # 注释掉
      continue-on-error: true
  # Cache Configuration
  cache:
    type: simple

# Management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.school.course: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa.repositor: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
